-- Queries ejecutadas y comprobadas

CREATE TABLE bronze.employee_attrition (
    Age INTEGER,
    Attrition VARCHAR(10),
    BusinessTravel VARCHAR(100),
    DailyRate INTEGER,
    Department VARCHAR(50),
    DistanceFromHome INTEGER,
    Education INTEGER,
    EducationField VARCHAR(10),
    EmployeeCount INTEGER,
    EmployeeNumber INTEGER, -- Sirve como PK
    EnvironmentSatisfaction INTEGER,
    Gender VARCHAR(10),
    HourlyRate VARCHAR(5),
    JobInvolvement INTEGER,
    JobLevel INTEGER,
    JobRole VARCHAR(50),
    JobSatisfaction INTEGER,
    MaritalStatus VARCHAR(50),
    MonthlyIncome INTEGER,
    MonthlyRate INTEGER,
    NumCompaniesWorked INTEGER,
    Over18 VARCHAR(5),
    OverTime VARCHAR(5),
    PercentSalaryHike INTEGER,
    PerformanceRating INTEGER,
    RelationshipSatisfaction INTEGER,
    StandardHours INTEGER,
    StockOptionLevel INTEGER,
    TotalWorkingYears INTEGER,
    TrainingTimesLastYear INTEGER,
    WorkLifeBalance INTEGER,
    YearsAtCompany INTEGER,
    YearsInCurrentRole INTEGER,
    YearsSinceLastPromotion INTEGER,
    YearsWithCurrManager INTEGER
)